### PR TITLE
add `DictMsgFormat` and `InProcTransport`

### PR DESCRIPTION
**Pull request by tanmaykm**
`DictMsgFormat` and `InProcTransport` enable simpler and faster communication when a light workload needs to be hosted by a single process.

There is no RPC or serialization involved in the internal communication. The overhead of converting data from and to the external request format (likely HTTP) remains though, and is unavoidable.

### CODE REVIEW

**Comment by tanmaykm** [comment]
Travis CI fails on Julia 0.4 because Julia process does not exit when there is a listening socket active. This seems to be a regression of an earlier Julia issue. However, this is unlikely to be encountered in practice and hence not a real issue.

Coverage fell because of tests excluding certain outdated methods, to be deprecated before the next tag.

**Comment by tanmaykm** [comment]
Will merge this in a bit and follow up with a separate PR to deprecate outdated methods and fix coverage.

**Comment by aviks** [comment]
Just stop supporting 0.4 with the current release? Older julia users should just stick to the existing releases.

**Comment by tanmaykm** [comment]
Yes, maybe a good idea. It will also help clean up some compat cruft.
I will prepare a PR.

**Pull request merged**
